/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;

import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.awt.event.ContainerListener;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author upszot
 */
public class JIlFrm_juego extends javax.swing.JInternalFrame
{

    private Teclado tecladoEnPantalla;
    private Juego nuevoJuego;

    private JButton botones[] = new JButton[27];
    private char letra;
     Container cp ;
    

    /**
     * Creates new form NewJInternalFrame
     */
    public JIlFrm_juego()
    {
        this.setContentPane(new JLabel(new ImageIcon("imagenes/fondo.jpg")));
        
        initComponents();
        iniciarJuego();
        iniciarTeclado();
        
        
        //  this.nuevoJuego.BuscaLetraEnPalabra(this.tecladoEnPantalla.getLetra());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtPalabra = new javax.swing.JTable();
        lblIngreseLetra = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        panelTeclado = new javax.swing.JLayeredPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLayeredPane1.addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                jLayeredPane1ComponentShown(evt);
            }
        });

        jtPalabra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jScrollPane1.setViewportView(jtPalabra);

        lblIngreseLetra.setText("Ingrese Letra:");

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblIngreseLetra, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblIngreseLetra, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGap(485, 485, 485)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIngreseLetra)
                .addGap(7, 7, 7))
        );

        panelTeclado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelTecladoLayout = new javax.swing.GroupLayout(panelTeclado);
        panelTeclado.setLayout(panelTecladoLayout);
        panelTecladoLayout.setHorizontalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelTecladoLayout.setVerticalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTeclado)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBox2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtBox2ActionPerformed
    {//GEN-HEADEREND:event_txtBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBox2ActionPerformed

    private void txtBox2KeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtBox2KeyTyped
    {//GEN-HEADEREND:event_txtBox2KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBox2KeyTyped

    private void jLayeredPane1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jLayeredPane1ComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jLayeredPane1ComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtPalabra;
    private javax.swing.JLabel lblIngreseLetra;
    private javax.swing.JLayeredPane panelTeclado;
    // End of variables declaration//GEN-END:variables

//------------- METODOS
    private void iniciarJuego()
    {
        setNuevoJuego(new Juego());
        showTablaPalabra(this.nuevoJuego.getPalabra_del_usuario());
    }

    private void showTablaPalabra(String mascara)
    {
        System.out.println("Palabra: " + this.getNuevoJuego().getPalabra_a_buscar().getPalabra()
                + " CantCaracteres: " + this.getNuevoJuego().getPalabra_a_buscar().getPalabra().length());

        DefaultTableModel tb = new DefaultTableModel();
        tb.setNumRows(1);

        for (int i = 0; i < this.getNuevoJuego().getPalabra_a_buscar().getPalabra().length(); i++)
        {
            tb.addColumn(mascara.charAt(i));

        }
        getJtPalabra().setModel(tb);
        getJtPalabra().setVisible(true);
    }

    /*   private void showTeclado()
    {
        Container cp = getPanelTeclado();
        GridLayout gl = new GridLayout(1, 1);
        cp.setLayout(gl);      

        cp.add(iniciarTeclado());
        getTecladoEnPantalla().setVisible(true);
    }
     */
    private void focoTeclado()
    {
        this.getNuevoJuego().BuscaLetraEnPalabra(this.getTecladoEnPantalla().getLetra());
        System.out.println("Tecla presionada: " + this.getTecladoEnPantalla().getLetra());
        System.out.println("Palabra encontrada: " + this.getNuevoJuego().getPalabra_del_usuario());
    }

    /**
     * @return the nuevoJuego
     */
    public Juego getNuevoJuego()
    {
        return nuevoJuego;
    }

    //<editor-fold desc="GETTERS&SETTERS">    
    public void setLetra(java.awt.event.ActionEvent letra)
    {
        JButton eventoBoton = (JButton) letra.getSource();
        eventoBoton.setEnabled(false);

        String aux = letra.getActionCommand();
        this.setLetra(aux.charAt(0));
        
        System.out.println("A pretado el boton " + eventoBoton.getActionCommand());
    }

    public char getLetra()
    {
        return letra;
    }
    //</editor-fold>

    public void iniciarTeclado()
    {
        cp = this.panelTeclado;
        GridLayout gl = new GridLayout(3, 10);
        gl.setHgap(2);
        gl.setVgap(2);
        cp.setLayout(gl);
        cp.setMaximumSize(new Dimension(530, 200));

        String letras = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
        //centrar iconos

        for (int i = 0; i < letras.length(); i++)
        {
            this.getBotones()[i] = new JButton();
            cp.add(getBotones()[i]);
            this.getBotones()[i].setText(String.valueOf(letras.charAt(i)));
            this.getBotones()[i].setFont(new Font("Tahoma", 0, 20));
            this.getBotones()[i].setVisible(true);
            this.getBotones()[i].addActionListener(new ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    setLetra(evt);
                    recibirDeTeclado(getLetra());

                    //    this.nuevoJuego.BuscaLetraEnPalabra(this.tecladoEnPantalla.getLetra());
                }
            });//fin escuchador            

        }// FIN for (int i = 0; i < letras.length(); i++)
    }

    /**
     * @return the tecladoEnPantalla
     */
    public void recibirDeTeclado(char letra1)
    {
        
        this.nuevoJuego.setCantFallos(this.nuevoJuego.getCantFallos() + this.nuevoJuego.BuscaLetraEnPalabra(letra1));
        
        if (this.nuevoJuego.getPalabra_a_buscar().getPalabra().compareToIgnoreCase(this.nuevoJuego.getPalabra_del_usuario()) == 0)
        {//Comparo palabras a buscar y la ingresada y le pego...wiii gano... PROXIMA PALABRA
            showTablaPalabra(this.nuevoJuego.getPalabra_del_usuario());
            this.nuevoJuego.setCantAciertos(this.nuevoJuego.getCantAciertos()+1); //palabras acertadas
            System.out.println(" Palabra Correcta " + this.nuevoJuego.getPalabra_del_usuario());
            JOptionPane.showMessageDialog(this, " Palabra Correcta " + this.nuevoJuego.getPalabra_del_usuario());
            this.nuevoJuego.nuevaPalabra();
            this.limpiarPanelJuego();
        }
        else
        {
            if(this.nuevoJuego.getCantFallos()==this.nuevoJuego.getCantFallosPermitidos())
            {//hee le erraste todas...chinguenguenza
                System.out.println("Perdiste....");
                JOptionPane.showMessageDialog(this, " Perdiste!! le erraste todas...chinguenguenza, La palabra era:  " + this.nuevoJuego.getPalabra_a_buscar());
                
                if(this.nuevoJuego.getCantAciertos()>1)
                {//anotate en lista ganadores
                    
                }
            }
        }
        //aca refresco la pantalla
        showTablaPalabra(this.nuevoJuego.getPalabra_del_usuario());
    }

    private void limpiarPanelJuego()
    {
        cp.removeAll();
        iniciarTeclado();
        showTablaPalabra(this.nuevoJuego.getPalabra_del_usuario());
        // limpiar dibujo

    }

    public Teclado getTecladoEnPantalla()
    {
        return tecladoEnPantalla;
    }

    /**
     * @param tecladoEnPantalla the tecladoEnPantalla to set
     */
    public void setTecladoEnPantalla(Teclado tecladoEnPantalla)
    {
        this.tecladoEnPantalla = tecladoEnPantalla;
    }

    /**
     * @param nuevoJuego the nuevoJuego to set
     */
    public void setNuevoJuego(Juego nuevoJuego)
    {
        this.nuevoJuego = nuevoJuego;
    }

    /**
     * @return the botones
     */
    public JButton[] getBotones()
    {
        return botones;
    }

    /**
     * @param botones the botones to set
     */
    public void setBotones(JButton[] botones)
    {
        this.botones = botones;
    }

    /**
     * @param letra the letra to set
     */
    public void setLetra(char letra)
    {
        this.letra = letra;
    }

    /**
     * @return the jLabel3
     */
    public javax.swing.JLabel getjLabel3()
    {
        return jLabel3;
    }

    /**
     * @param jLabel3 the jLabel3 to set
     */
    public void setjLabel3(javax.swing.JLabel jLabel3)
    {
        this.jLabel3 = jLabel3;
    }

    /**
     * @return the jLayeredPane1
     */
    public javax.swing.JLayeredPane getjLayeredPane1()
    {
        return jLayeredPane1;
    }

    /**
     * @param jLayeredPane1 the jLayeredPane1 to set
     */
    public void setjLayeredPane1(javax.swing.JLayeredPane jLayeredPane1)
    {
        this.jLayeredPane1 = jLayeredPane1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1()
    {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1)
    {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jtPalabra
     */
    public javax.swing.JTable getJtPalabra()
    {
        return jtPalabra;
    }

    /**
     * @param jtPalabra the jtPalabra to set
     */
    public void setJtPalabra(javax.swing.JTable jtPalabra)
    {
        this.jtPalabra = jtPalabra;
    }

    /**
     * @return the lblIngreseLetra
     */
    public javax.swing.JLabel getLblIngreseLetra()
    {
        return lblIngreseLetra;
    }

    /**
     * @param lblIngreseLetra the lblIngreseLetra to set
     */
    public void setLblIngreseLetra(javax.swing.JLabel lblIngreseLetra)
    {
        this.lblIngreseLetra = lblIngreseLetra;
    }

    /**
     * @return the panelTeclado
     */
    public javax.swing.JLayeredPane getPanelTeclado()
    {
        return panelTeclado;
    }

    /**
     * @param panelTeclado the panelTeclado to set
     */
    public void setPanelTeclado(javax.swing.JLayeredPane panelTeclado)
    {
        this.panelTeclado = panelTeclado;
    }

}
