/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ahorcado;

import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author upszot
 */
public class Teclado extends javax.swing.JPanel {

    JButton botones[]  =new JButton [27];
    private char  letra;
    
    /**
     * Creates new form Teclado
     */
    public Teclado() {
        initComponents();
        iniciarTeclado();
    }

        //<editor-fold desc="GETTERS&SETTERS">    
            public void setLetra(java.awt.event.ActionEvent letra) {
                String aux=letra.getActionCommand();        
                this.letra = aux.charAt(0);
            }

            public char getLetra() {
                return letra;
            }
    //</editor-fold>

    public void iniciarTeclado()
    {
        Container cp = this;
        GridLayout gl = new GridLayout(3, 10);
        gl.setHgap(2);
        gl.setVgap(2);
        cp.setLayout(gl);
        cp.setMaximumSize(new Dimension(530, 200));
        //cp.setBackground(new Color(63, 51, 49)); //MODIFICAR color
        
        String letras = "ABCDEFGHIJKLMNÑOPQRSTUVWXYZ";
        //centrar iconos

        for (int i = 0; i < letras.length(); i++)
        {
            this.botones[i] = new JButton();
            cp.add(botones[i]);
            this.botones[i].setText(String.valueOf(letras.charAt(i)));
            this.botones[i].setFont(new Font("Tahoma", 0, 20));
            this.botones[i].setVisible(true);
            this.botones[i].addActionListener(new ActionListener()
            {
                public void actionPerformed(java.awt.event.ActionEvent evt)
                {
                    setLetra(evt);                    
                }
            });//fin escuchador            
                      
        }// FIN for (int i = 0; i < letras.length(); i++)
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

